import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MenuBar from "./_components/MenuBar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Simple app 2.0",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="bg-sky-800 text-white text-center p-10">
              <h1 className="text-5xl">Simple App 2.0</h1>
              
              <div className="mt-5 text-xl">
                <MenuBar />
              </div>
        </header>

        <div className="m-10">
            {children}
        </div>

        <footer className="bg-sky-800 text-white text-center p-2 bottom-0 fixed w-full">
            <h4 className="text-xl">&copy; developed by : developer name. Developed in 2025.</h4>
        </footer>
      </body>
    </html>
  );
}
