import type { Metadata } from "next";
import "./globals.css";
import MenuBar from "./_components/MenuBar";
import DataProvider from "./_components/DataProvider";



export const metadata: Metadata = {
  title: "Simple app 2.0",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>  
          <DataProvider>

              <h1>Simple App</h1>   
              <hr />    
              <MenuBar />    
              <hr /> 
              {children}

          </DataProvider>      
      </body>
    </html>
  );
}
